has_aux_classifier: false
batch_size: 8
epochs: 1000
image_size: 512
num_classes: 1
learning_rate: 0.0001
max_learning_rate: 0.0001
learning_rate_weight_decay: 0.1
ignore_index: 0
dataset: minesegsat
model: segformer
save_frequency: 1
num_dataloader_workers: 2
output_path: ~/code/mine_seg_sat/data/outputs
data_path: ~/code/mine_seg_sat/data/outputs
loss: tversky
lr_scheduler: plateau
weight_filepath: /path/to/pretrained_weights/segformer/aug10/final_model.pth
